### PR TITLE
Auto load is enabled when scroller hit the bottom of the page (Fixes Issue #34)

### LINKED ISSUE #34: [Enhancement] Scrolling very bottom of the page should trigger load more images
It would be nice to have auto loading when user scrolls the very bottom of the page.

### PR DESCRIPTION
**Pull request by elyessAR**
## Fixes Issue

Closes #34

## Check List (Check all the applicable boxes) 

- [ x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ x] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

changes1
changes2
changes3

### CODE REVIEW

**Comment by furkanmutlu** [comment]
Hi @elyessAR  I had a quick look at your PR deploy preview. Seems like There is a bug when you scroll down same images are being fetched and added as new images. Try to pay attention on loaded images. Feels like something is wrong with `offset`. I will take a detailed look soon.

File: frontend/src/components/LoadMoreButton/LoadMoreButton.jsx [hunk 1]
```diff
@@ -12,7 +12,12 @@ const LoadMoreButton = ({
   setOffset,
   setImages,
 }) => {
-  const [isLoading, setIsLoading] = useState(false);
+    const [isLoading, setIsLoading] = useState(false);
+
+  useEffect(() => {
+    window.addEventListener('scroll', handleScroll);
+    return () => window.removeEventListener('scroll', handleScroll);
+  });
```
Comment (furkanmutlu) [inline frontend/src/components/LoadMoreButton/LoadMoreButton.jsx:20]: this looks wrong to me. I dont think we should add and remove scroll event listener on every rerender.

**Comment by furkanmutlu** [comment]
@elyessAR I fixed some issues and updated your branch. Please let me know if changes looks good to you. Thanks

**Review by furkanmutlu — APPROVED** [review]

**Comment by furkanmutlu** [comment]
I am merging this PR, thank you for your contribution, looking forward to work together again!
